table 'month sort'
	lineageTag: 8a42044e-25d0-4f6b-8079-352d6a40d3fd

	column 'Month Name'
		dataType: string
		formatString: date
		lineageTag: 13dc62e2-799c-4d8e-9737-2314b2ac21e7
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 7423312f-226a-4588-a480-48716469327b
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'month sort' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8krMK00sqlTSUTJUitWJVnJLTSqCChiBBXwTi5IzgDxjMM+xoCgzB8gzgcqB1JmC2V6lealAjhmUkwOSMYfoKU0vLS4Bci3A3ODUgpLU3KTUIqCIJVjEP7kkH8I3NAAL+OWXwVQYQpzlkpoMFwG6KxYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Month Name" = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Month Name", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

